### PR TITLE
Surround flag arguments with quotes

### LINKED ISSUE #100: PR creation fails if --pr-reviewers is empty
### What happened?

I ran this tool locally to test changes for #96 and discovered the following error on the final step, `gh pr create`:

```
  - X /usr/local/bin/gh pr create --assignee @me --base master --head upgrade-terrafor...: exit status 1:
unknown argument ""; please quote all values that have spaces
```

I upgraded my `gh` version. I made sure to check with latest `main`. No dice.

It turns out that if I passed 
`upgrade-provider pulumi/pulumi-civo --upstream-provider-name=terraform-provider-civo --kind=all --pr-reviewers=aq17` the PR was created successfully. Seems like we've inadvertently added some whitespace here? https://github.com/pulumi/upgrade-provider/commit/38ae9cf189e17f53637a87c1da4cb6c725a1a8e1#diff-d5c54fe7fdac4cea34363fc36154d215683b9b55e14428dd7cd578204f6c8d92L316

### Expected Behavior

The PR should be created.

### Steps to reproduce

Run `upgrade-provider pulumi/pulumi-civo --upstream-provider-name=terraform-provider-civo --kind=all` on any pending provider upgrade.

### Output of `pulumi about`

n/a

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by aq17**
Fixes #100 

Flag arguments with spaces need to be surrounded by quotes

### CODE REVIEW

File: upgrade/steps.go [hunk 1]
```diff
@@ -312,7 +312,7 @@ func InformGitHub(
 
 	reviewerFlag := ""
 	if ctx.PrReviewers != "" {
-		reviewerFlag = fmt.Sprintf("--reviewer=%s", ctx.PrReviewers)
+		reviewerFlag = fmt.Sprintf("--reviewer=\"%s\"", ctx.PrReviewers)
```
Comment (guineveresaenger) [inline upgrade/steps.go:315]: This will not fix the issue. The issue is that `reviewerFlag` gets literally quoted into the command as
`gh pr create --assignee @me --base main --head test "" --title hiwhatsup --body loremipsum`.

**Review by guineveresaenger — CHANGES_REQUESTED** [review]

File: upgrade/steps.go (hunk 1 above)
Comment (guineveresaenger) [reply upgrade/steps.go:315]: this works:
`gh pr create --assignee @me --base main --head test --reviewer "" --title hiwhatsup --body loremipsum` so we can just get rid of the entire if statement here!

**Review by guineveresaenger — APPROVED** [review]
LGTM! :shipit:
