### PR TITLE
Fix duplicate AutoAliasing migration

### LINKED ISSUE #58: AutoAliasing isn't idempotent
### What happened?

I noticed this as part of https://github.com/pulumi/pulumi-random/pull/300.

### Expected Behavior

AutoAlias should trigger exactly once. I fixed the `MetadataInfo`, but you can see the problem for the duplicated `_ "embed"`s: https://github.com/pulumi/pulumi-random/pull/300/commits/1feb3401061b4c7b05df3606990507ea8e1e133d#diff-34c57e622183cb0d8dd0d3f9eaa0861b3340120e9b2ad811bac7ac7be4cea4b1

### Steps to reproduce

Run AutoAliasing on `resources.go` as found in `pulumi-random`.

### Output of `pulumi about`

NA

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by aq17**
Fixes #58

### CODE REVIEW

**Comment by aq17** [comment]
https://github.com/pulumi/upgrade-provider/actions/runs/4824880042/jobs/8595179219?pr=62 is ironic

File: upgrade/migrations.go [hunk 1]
```diff
@@ -150,12 +152,16 @@ func AutoAliasingMigration(resourcesFilePath, providerName string) (bool, error)
...
 		return false, err
 	}
+	replaceAnchors := func(s string) string {
+		s = strings.Replace(s, "EMBED_COMMENT_ANCHOR \"embed\"",
+			"// embed is used to store bridge-metadata.json in the compiled binary\n    _ \"embed\"", 1)
+		s = strings.Replace(s, `var metadata []byte // EMBED_DIRECTIVE_ANCHOR`,
+			fmt.Sprintf("//go:embed cmd/pulumi-resource-%s/bridge-metadata.json\nvar metadata []byte",
+				providerName), 1)
+		return s
+	}
```
Comment (iwahbe) [inline upgrade/migrations.go:162]: I would personally inline this out of the lambda, but its up to you.

File: upgrade/steps.go [hunk 2]
```diff
@@ -860,15 +861,20 @@ func AddAutoAliasing(ctx Context, repo ProviderRepo, providerName string) (step.
...
 
 func ReplaceAssertNoError(ctx Context, repo ProviderRepo, providerName string) (step.Step, error) {
-	return migrationSteps(ctx, repo, providerName, "Remove deprecated contract.Assert",
-		AutoAliasingMigration)
+	steps, err := migrationSteps(ctx, repo, providerName, "Remove deprecated contract.Assert",
+		AssertNoErrorMigration)
+	if err != nil {
+		return nil, err
+	}
+	return step.Combined("Replace AssertNoError", steps...), nil
```
Comment (iwahbe) [inline upgrade/steps.go:879]:
```suggestion
	return step.Combined("Replace AssertNoError with AssertNoErrorf", steps...), nil
```

**Review by iwahbe — APPROVED** [review]
