### PR TITLE
Keep `pu/pkg` up to date between examples and provider directories

### LINKED ISSUE #102: Keep `./examples/go.mod` `github.com/pulumi/pulumi/pkg/v3` version in line with `./provider/go.mod` version
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We need to keep `./examples/go.mod` `github.com/pulumi/pulumi/pkg/v3` up to date with the version found in `./provider/go.mod` to avoid conflicts. Failing to do this now (given sufficient drift) results in the following error:

```
- ✓ /usr/local/bin/go get github.com/pulumi/pulumi-terraform-bridge/v3@v3.50.1: done
- Upgrade Pulumi SDK
  - ✓ /usr/local/bin/go get github.com/pulumi/pulumi/sdk/v3: done
  - ✓ /usr/local/bin/go get github.com/pulumi/pulumi/pkg/v3: done
- ✓ /usr/local/bin/go mod tidy: done
- X /usr/local/bin/go mod tidy: exit status 1:
go: finding module for package github.com/Sirupsen/logrus
go: downloading github.com/Sirupsen/logrus v1.9.3
go: found github.com/Sirupsen/logrus in github.com/Sirupsen/logrus v1.9.3
go: github.com/pulumi/pulumi-ns1/examples/v2 tested by
	github.com/pulumi/pulumi-ns1/examples/v2.test imports
	github.com/pulumi/pulumi/pkg/v3/testing/integration imports
	github.com/pulumi/pulumi/pkg/v3/backend/filestate imports
	github.com/pulumi/pulumi/pkg/v3/backend/display imports
	github.com/docker/docker/pkg/term imports
	github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.9.3: parsing go.mod:
	module declares its path as: github.com/sirupsen/logrus
	        but was required as: github.com/Sirupsen/logrus
```

### PR DESCRIPTION
**Pull request by aq17**
Keep ./examples/go.mod github.com/pulumi/pulumi/pkg/v3 version in line with ./provider/go.mod version
Fixes #102

### CODE REVIEW

**Comment by aq17** [comment]
Example PR that was failing before using this change https://github.com/pulumi/pulumi-postgresql/pull/244

File: main.go [hunk 1]
```diff
@@ -107,6 +107,7 @@ func cmd() *cobra.Command {
 				case "all":
 					context.UpgradeBridgeVersion = true
 					context.UpgradeProviderVersion = true
+					context.UpgradeSdkVersion = true
```
Comment (aq17) [inline main.go:110]: I'm not sure why we weren't previously opting sdk upgrades into `"all"`

Comment (iwahbe) [reply main.go:110]: We decided we didn't want to default pushing the sdk version past what the bridge requires. The bridge depends on too many internals of pulumi/pkg and this often breaks.

It would be great if you could add a comment explaining as such.

```suggestion
```

File: upgrade/upgrade-provider.go [hunk 2]
```diff
@@ -297,7 +297,10 @@ func UpgradeProvider(ctx Context, repoOrg, repoName string) error {
 				In(repo.providerDir()),
 			step.Cmd(exec.CommandContext(ctx,
 				"go", "get", "github.com/pulumi/pulumi/pkg/v3")).
-				In(repo.providerDir())))
+				In(repo.providerDir())),
+			step.Cmd(exec.CommandContext(ctx,
+				"go", "get", "github.com/pulumi/pulumi/pkg/v3")).
+				In(repo.examplesDir()))
```
Comment (iwahbe) [inline upgrade/upgrade-provider.go:303]: Whenever we upgrade `pkg` we need to also upgrade `sdk`.

**Review by iwahbe — CHANGES_REQUESTED** [review]

File: main.go (hunk 1 above)
Comment (iwahbe) [reply main.go:110]: For example, if you did the same upgrade several hours later and depended on pulumi/pkg v3.76.0 it would fail to compile against the bridge.

**Review by iwahbe — APPROVED** [review]
